// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package com.shengsiyuan.netty.proto;

public interface MyResponseOrBuilder extends
        // @@protoc_insertion_point(interface_extends:com.shengsiyuan.netty.proto.MyResponse)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string realname = 2;</code>
     *
     * @return The realname.
     */
    String getRealname();

    /**
     * <code>string realname = 2;</code>
     *
     * @return The bytes for realname.
     */
    com.google.protobuf.ByteString
    getRealnameBytes();
}
