// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package com.shengsiyuan.netty.proto;

public interface MyRequestOrBuilder extends
        // @@protoc_insertion_point(interface_extends:com.shengsiyuan.netty.proto.MyRequest)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string username = 1;</code>
     *
     * @return The username.
     */
    String getUsername();

    /**
     * <code>string username = 1;</code>
     *
     * @return The bytes for username.
     */
    com.google.protobuf.ByteString
    getUsernameBytes();
}
