// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package com.shengsiyuan.netty.proto;

public interface StreamResponseOrBuilder extends
        // @@protoc_insertion_point(interface_extends:com.shengsiyuan.netty.proto.StreamResponse)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string respnse_info = 1;</code>
     *
     * @return The respnseInfo.
     */
    String getRespnseInfo();

    /**
     * <code>string respnse_info = 1;</code>
     *
     * @return The bytes for respnseInfo.
     */
    com.google.protobuf.ByteString
    getRespnseInfoBytes();
}
