// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package com.shengsiyuan.netty.proto;

public final class StudentProto {

  static final com.google.protobuf.Descriptors.Descriptor
          internal_static_com_shengsiyuan_netty_proto_MyRequest_descriptor;

  static final
  com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internal_static_com_shengsiyuan_netty_proto_MyRequest_fieldAccessorTable;

  static final com.google.protobuf.Descriptors.Descriptor
          internal_static_com_shengsiyuan_netty_proto_MyResponse_descriptor;

  static final
  com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internal_static_com_shengsiyuan_netty_proto_MyResponse_fieldAccessorTable;

  private static com.google.protobuf.Descriptors.FileDescriptor
          descriptor;

  static {
    String[] descriptorData = {
            "\n\rStudent.proto\022\033com.shengsiyuan.netty.p" +
                    "roto\"\035\n\tMyRequest\022\020\n\010username\030\001 \001(\t\"\036\n\nM" +
                    "yResponse\022\020\n\010realname\030\002 \001(\t2|\n\016StudentSe" +
                    "rvice\022j\n\025GetRealNameByUsername\022&.com.she" +
                    "ngsiyuan.netty.proto.MyRequest\032'.com.she" +
                    "ngsiyuan.netty.proto.MyResponse\"\000B-\n\033com" +
                    ".shengsiyuan.netty.protoB\014StudentProtoP\001" +
                    "b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
            .internalBuildGeneratedFileFrom(descriptorData,
                    new com.google.protobuf.Descriptors.FileDescriptor[] {
                    });
    internal_static_com_shengsiyuan_netty_proto_MyRequest_descriptor =
            getDescriptor().getMessageTypes().get(0);
    internal_static_com_shengsiyuan_netty_proto_MyRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_com_shengsiyuan_netty_proto_MyRequest_descriptor,
            new String[] { "Username", });
    internal_static_com_shengsiyuan_netty_proto_MyResponse_descriptor =
            getDescriptor().getMessageTypes().get(1);
    internal_static_com_shengsiyuan_netty_proto_MyResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_com_shengsiyuan_netty_proto_MyResponse_descriptor,
            new String[] { "Realname", });
  }

  private StudentProto() {
  }

  public static void registerAllExtensions(
          com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
          com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
            (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
  getDescriptor() {
    return descriptor;
  }

  // @@protoc_insertion_point(outer_class_scope)
}
