// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package com.shengsiyuan.netty.proto;

public interface StudentResponseListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.shengsiyuan.netty.proto.StudentResponseList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *集合
   * </pre>
   *
   * <code>repeated .com.shengsiyuan.netty.proto.StudentResponse studentResponse = 1;</code>
   */
  java.util.List<StudentResponse>
      getStudentResponseList();
  /**
   * <pre>
   *集合
   * </pre>
   *
   * <code>repeated .com.shengsiyuan.netty.proto.StudentResponse studentResponse = 1;</code>
   */
  StudentResponse getStudentResponse(int index);
  /**
   * <pre>
   *集合
   * </pre>
   *
   * <code>repeated .com.shengsiyuan.netty.proto.StudentResponse studentResponse = 1;</code>
   */
  int getStudentResponseCount();
  /**
   * <pre>
   *集合
   * </pre>
   *
   * <code>repeated .com.shengsiyuan.netty.proto.StudentResponse studentResponse = 1;</code>
   */
  java.util.List<? extends StudentResponseOrBuilder>
      getStudentResponseOrBuilderList();
  /**
   * <pre>
   *集合
   * </pre>
   *
   * <code>repeated .com.shengsiyuan.netty.proto.StudentResponse studentResponse = 1;</code>
   */
  StudentResponseOrBuilder getStudentResponseOrBuilder(
      int index);
}
